### ISSUE TITLE
🐛 Bug Report: Cannot find module 'appwrite' or its corresponding type declarations.ts(2307) in Angular project

### ISSUE THREAD

**Issue by tobang** [appwrite/sdk-for-web#36]
### 👟 Reproduction steps

I have an Angular project version 14.2.0. Installing the new version 10.0.0 gives the following error:
Cannot find module 'appwrite' or its corresponding type declarations.ts(2307)
Worked with previous 9.0.2 version.
Looked in node_modules/appwrite folder, and types folder is missing. It was present i previous version.

### 👍 Expected behavior

Types should be present and no error in code.

### 👎 Actual Behavior

Module import error.

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@tobang, thanks for raising this issue! 🙏 The issue should be fixed in 10.0.1 now. Would you please try with that version?

**Comment by tobang** [comment]
I can confirm that it now works 😀, thank you.
